manifest:
  defaults:
    # Pinned to a specific commit on ZMK's main branch (rather than tracking
    # main's moving head) for build reproducibility. See
    # https://zmk.dev/blog/2025/06/20/pinned-zmk for why tracking main
    # directly is discouraged upstream.
    revision: 5b51501fead672c41b5cfb396f3dafe0894bf4e9
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: joelspadin
      url-base: https://github.com/joelspadin
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-locales
      remote: joelspadin
      revision: main
  self:
    path: config
